name: GooCompleter
author: juanparati
category: Forms
tags: [Forms, form, autocompletion, autocomplete]
docs: https://github.com/juanparati/GooCompleter 
demo: http://www.livespanske.com/labs/GooCompleter
current: 1.3
